repos:
-   hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
-   hooks:
    -   id: terraform_fmt
    -   id: terraform_docs
    -   id: terraform_tflint
    -   args:
        - -a --soft-fail
        id: terraform_tfsec
    repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.73.0
-   hooks:
    -   id: commitizen
        stages:
        - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
-   hooks:
    -   id: flake8
    repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
