---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoind-deployment
  namespace: bitcoind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoind
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:
        - name: bitcoind
          image: localhost:5000/muhthing
